name: OJALA WERKE
favicon: null
layout_spectrum: 0.601521119242534
typography_spectrum: 0.6033935910090804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9781366339884698
  lightness: 0.6136540691368282
  saturation: 0.45278075407259166
  rhythmicContrast: 0.7112744015175849
purpose: []
