name: OJALA WERKE
favicon: null
layout_spectrum: 0.30527
typography_spectrum: 0.84678
title: OJALA WERKE Designbüro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#424242'
    - '#e1e1e1'
    - '#6e6e6e'
    - '#b5b5b5'
  brandStrength: 0.9781366339884698
  lightness: 0.6136540691368282
  saturation: 0.45278075407259166
  rhythmicContrast: 0.7112744015175849
purpose: []
